language: node_js
node_js:
- '7'
- '6'
- '5'
- '4'
- '0.12'
- '0.11'
- '0.10'
- iojs
after_success:
- npm run coveralls
services:
- rabbitmq
deploy:
  provider: npm
  email: integration-dev@thomascookonline.com
  api_key:
    secure: UelZNGD1jKhJ9Jefbp0S8ECEDz3Q3tP67ibGLxGBliFFUgyb05MHLLwX447jO4UhW1/jIE2aAn6cy0ad/Fm+CkymOC8r8LfGR1cfp/0auN1gU0fxMiZWrz0RxBmhBIFnUD+I+j6mjxU8ceABCsxwpMy6MHQlCOAl1ffOk2s+n1U=
  on:
    tags: true
    repo: tcdl/msb
